name: 'ci'

on:
  workflow_call:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: 'read'
  id-token: 'write'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  DEFAULT_GO_VERSION: '1.21'
  PROTOTOOL_VERSION: '1.10.0' # this is the last released version before the project was completed
  PROTOBUF_VERSION: '24.3'
  PROTOC_GEN_GO_PLUGIN_VERSION: '1.31'
  BUF_VERSION: '1.28.1'

jobs:
  build: 
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout PR branch'
        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.head.ref }}'

      - name: 'Setup Buf CLI'
        uses: 'bufbuild/buf-setup-action@382440cdb8ec7bc25a68d7b4711163d95f7cc3aa' # ratchet:bufbuild/buf-setup-action@v1.28.1
        with:
          github_token: ${{ github.token }}

      - name: 'Run Build'
        shell: 'bash'
        run: |
          set +e
          BUILD_CHECK=$(buf build)
          if ! [[ -z "${BUILD_CHECK}" ]]; then
            echo "::error::$BUILD_CHECK"
            exit 1
          fi

  lint:
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
      - name: 'Checkout PR branch'
        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.head.ref }}'

      - name: 'Setup Buf CLI'
        uses: 'bufbuild/buf-setup-action@382440cdb8ec7bc25a68d7b4711163d95f7cc3aa' # ratchet:bufbuild/buf-setup-action@v1.28.1
        with:
          github_token: ${{ github.token }}

      - name: 'Run Linter'
        uses: 'bufbuild/buf-lint-action@v1'

  regenerate:
    runs-on: 'ubuntu-latest'
    needs: 'lint'
    steps:
      - name: 'Checkout PR branch'
        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.head.ref }}'

      - name: 'Setup Go'
        uses: 'actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753' # ratchet:actions/setup-go@v4
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}

      - name: 'Setup Buf CLI'
        uses: 'bufbuild/buf-setup-action@382440cdb8ec7bc25a68d7b4711163d95f7cc3aa' # ratchet:bufbuild/buf-setup-action@v1.28.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Install protobuf'
        uses: 'abcxyz/pkg/.github/actions/setup-binary@main' # ratchet:exclude
        with:
          download_url: 'https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOBUF_VERSION }}/protoc-${{ env.PROTOBUF_VERSION }}-linux-x86_64.zip'
          install_path: '${{ runner.temp }}/.protoc'
          checksum: 'fc793561283d9ea6813fb757ae54f1afea6770afcd930904bdf3e590910420aa'
          cache_key: '${{ runner.os }}_${{ runner.arch }}_protoc_${{ env.PROTOBUF_VERSION }}'
          add_to_path: true          

      - name: 'Install protoc-gen-go'
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v${{ env.PROTOC_GEN_GO_PLUGIN_VERSION }}

      - name: 'Run Generate'
        shell: 'bash'
        run: |
          set +e
          BUF_GEN=$(buf generate)
          DIFF=$(git status --porcelain)
          echo $DIFF
          if ! [[ -z "${DIFF}" ]]; then
            echo "::error::Files were not generated from latest proto changes"
            exit 1
          fi

  breaking:
    runs-on: 'ubuntu-latest'
    needs: 'regenerate'
    steps:
      - name: 'Checkout PR branch'
        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.head.ref }}'

      - name: 'Setup Buf CLI'
        uses: 'bufbuild/buf-setup-action@382440cdb8ec7bc25a68d7b4711163d95f7cc3aa' # ratchet:bufbuild/buf-setup-action@v1.28.1

      - name: 'Run Break Check'
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/kiyani-org/proto-solution.git#branch=main,ref=HEAD~1'
