name: 'upload'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  DEFAULT_GO_VERSION: '1.21'
  WIF_PROVIDER: 'projects/891125439796/locations/global/workloadIdentityPools/gh-automation-977ae9/providers/gh-automation-977ae9'
  WIF_SERVICE_ACCOUNT: 'gh-automation-sa@shankiyani-dev-d736c9.iam.gserviceaccount.com'
  PROJECT_ID: 'shankiyani-dev-d736c9'
  GO_GAR_REPOSITORY_NAME: 'go-protos'
  GO_GAR_REPOSITORY_LOCATION: 'us-east1'
  GO_MODULE_PATH: 'github.com/kiyani-org/proto-solution'

jobs:
  ci:
    uses: './.github/workflows/ci.yml'
    permissions:
      contents: 'read'
      id-token: 'write'

  deploy_go:
    needs:
      - 'ci'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d' # ratchet:google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@d51b5346f85640ec2aa2fa057354d2b82c2fcbce' # ratchet:google-github-actions/setup-gcloud@v1
        with:
          install_components: 'package-go-module'

      - name: 'Setup Go'
        uses: 'actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753' # ratchet:actions/setup-go@v4
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}

      - id: 'date'
        run: |-
          echo "now=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: 'Printing stuff for debugging'
        run: |-
          tree
          ls -ltra ./gen/go

      - name: 'Upload to GAR (go)'
        env:
          # version must have format vX.Y.Z https://cloud.google.com/artifact-registry/docs/go/store-go#package_and_upload_your_module
          VERSION: 'v0.0.0-${{ steps.date.outputs.now }}-${{ github.sha }}'
          GO_GEN_PROTOS_DIRECTORY: '.'
        run: |-
          cd ./gen/go
          echo gcloud artifacts go upload \
          --module-path="${{ env.GO_MODULE_PATH }}" \
          --project="${{ env.PROJECT_ID }}" \
          --location="${{ env.GO_GAR_REPOSITORY_LOCATION }}" \
          --repository="${{ env.GO_GAR_REPOSITORY_NAME }}" \
          --version=$VERSION

          gcloud artifacts go upload \
          --module-path="${{ env.GO_MODULE_PATH }}" \
          --project="${{ env.PROJECT_ID }}" \
          --location="${{ env.GO_GAR_REPOSITORY_LOCATION }}" \
          --repository="${{ env.GO_GAR_REPOSITORY_NAME }}" \
          --version=$VERSION

