name: 'upload'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: 'read'
  id-token: 'write'

concurrency:
  group: 'upload-${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  GO_VERSION: '1.21'
  WIF_PROVIDER: 'projects/537890254076/locations/global/workloadIdentityPools/github-automation/providers/gh-automation'
  WIF_SERVICE_ACCOUNT: 'github-automation-bot@shankiyani-dev-95.iam.gserviceaccount.com'
  PROJECT_ID: 'shankiyani-dev-95'
  GO_GAR_REPOSITORY_NAME: 'proto-go'
  GO_GAR_REPOSITORY_LOCATION: 'us'
  GO_MODULE_PATH: 'github.com/kiyani-org/proto-solution'

jobs:
  ci:
    uses: './.github/workflows/ci.yml'
    permissions:
      contents: 'read'
      id-token: 'write'

  store_proposed_proto_version:
    runs-on: 'ubuntu-latest'
    outputs:
      proposed_proto_version: ${{ steps.capture.outputs.PROPOSED_PROTO_VERSION }}
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744' # ratchet:actions/checkout@v3
      - name: 'Capture proposed version'
        id: "capture"
        run: |
          echo "PROPOSED_PROTO_VERSION=$(yq eval '.proto_version' version.yaml)" >> $GITHUB_OUTPUT
          
  deploy_go:
    needs:
      - 'ci'
      - 'store_proposed_proto_version'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # ratchet:actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@3a3c4c57d294ef65efaaee4ff17b22fa88dd3c69' # ratchet:google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
          token_format: 'access_token'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@98ddc00a17442e89a24bbf282954a3b65ce6d200' # ratchet:google-github-actions/setup-gcloud@v2
        with:
          install_components: 'package-go-module'

      - name: 'Setup Go'
        uses: 'actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe' # ratchet:actions/setup-go@v4
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: 'Upload to GAR (go)'
        env:
          # version must be prefixed with vX.Y.Z https://cloud.google.com/artifact-registry/docs/go/store-go#package_and_upload_your_module
          # the sha suffix is easily associate a commit with a version.
          VERSION: '${{ needs.store_proposed_proto_version.outputs.proposed_proto_version }}-${{ github.sha }}'
          GO_GEN_PROTOS_DIRECTORY: './gen/go'
        run: |-
          gcloud artifacts go upload --verbosity=debug \
          --module-path=${{ env.GO_MODULE_PATH }} \
          --source=$GO_GEN_PROTOS_DIRECTORY \
          --project=${{ env.PROJECT_ID }} \
          --location=${{ env.GO_GAR_REPOSITORY_LOCATION }} \
          --repository=${{ env.GO_GAR_REPOSITORY_NAME }} \
          --version=$VERSION
